import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';
const $ = s => document.querySelector(s);
const authDialog = $('#authDialog');
let supabase, session, dashboard;
const toast = (message) => { const t = $('#toast'); t.textContent = message; t.classList.add('show'); setTimeout(() => t.classList.remove('show'), 3200); };
const api = async (path, options = {}) => { if (!session) throw new Error('Please enter the portal first.'); const response = await fetch(path, { ...options, headers: { 'Content-Type':'application/json', Authorization:`Bearer ${session.access_token}`, ...(options.headers || {}) } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Something went wrong.'); return data; };
function render(data) { dashboard = data; $('#balance').textContent = data.profile.balance; $('#marketGrid').innerHTML = data.listings.map(item => `<article class="card item"><span class="item-icon">${item.icon}</span><h3>${item.title}</h3><p>${item.description}</p><div class="price">✦ ${item.price} CR <button class="buy" data-buy="${item.id}">Buy →</button></div></article>`).join(''); $('#inbox').innerHTML = data.mail.length ? data.mail.slice(0,4).map(m => `<div class="mail-preview"><b>${m.subject}</b><p>${m.body}</p></div>`).join('') : '<p class="mail-preview">Your inbox is quiet for now.</p>'; $('#chatLog').innerHTML = data.chat.map(m => `<div class="message"><b>${m.profiles?.display_name || 'Citizen'}</b>${m.body} <time>${new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time></div>`).join(''); $('#authButton').textContent = data.profile.display_name; }
async function refresh() { try { render(await api('/api/dashboard')); } catch (e) { toast(e.message); } }
function openAuth() { authDialog.showModal(); }
$('#authButton').onclick = () => session ? toast(`Welcome back, ${dashboard.profile.display_name}.`) : openAuth();
$('#heroButton').onclick = openAuth; $('[data-close]').onclick = () => authDialog.close();
document.querySelectorAll('[data-mode]').forEach(b => b.onclick = () => { document.querySelectorAll('[data-mode]').forEach(x => x.classList.remove('active')); b.classList.add('active'); $('#authForm').classList.toggle('signup', b.dataset.mode === 'signup'); });
$('#authForm').onsubmit = async (e) => { e.preventDefault(); const form = new FormData(e.target), signup = $('.tabs .active').dataset.mode === 'signup'; if (!supabase) return toast('Add your Supabase keys to enable citizen access.'); const credentials = { email:form.get('email'), password:form.get('password') }; const result = signup ? await supabase.auth.signUp({ ...credentials, options:{ data:{ display_name:form.get('displayName') } } }) : await supabase.auth.signInWithPassword(credentials); if (result.error) return toast(result.error.message); if (!result.data.session) return toast('Check your email to confirm your citizen account.'); session = result.data.session; authDialog.close(); toast('Welcome to Crystonia.'); refresh(); };
$('#transferForm').onsubmit = async e => { e.preventDefault(); try { await api('/api/transfer',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}); e.target.reset(); toast('Crystallines sent.'); refresh(); } catch(x) { toast(x.message); } };
$('#mailForm').onsubmit = async e => { e.preventDefault(); try { await api('/api/mail',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}); e.target.reset(); toast('Crystal mail sent.'); refresh(); } catch(x) { toast(x.message); } };
$('#chatForm').onsubmit = async e => { e.preventDefault(); try { await api('/api/chat',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}); e.target.reset(); refresh(); } catch(x) { toast(x.message); } };
$('#marketGrid').onclick = async e => { const itemId = e.target.dataset.buy; if (!itemId) return; try { await api('/api/purchase',{method:'POST',body:JSON.stringify({itemId})}); toast('A new treasure is yours.'); refresh(); } catch(x) { toast(x.message); } };
async function boot() { const url = window.CRYSTONIA_SUPABASE_URL, key = window.CRYSTONIA_SUPABASE_ANON_KEY; if (url && key) { supabase = createClient(url,key); const { data } = await supabase.auth.getSession(); session = data.session; if (session) { refresh(); setInterval(refresh, 10000); } } }
boot();
